version: "3.8"
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    container_name: "homeassistant"
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    volumes:
      - /home/vipul/homeassistant:/config
      - /run/dbus:/run/dbus:ro
    network_mode: host
    # This will replace the existing homeassistant container

  satellite:
    image: "vipulsindha/wyoming-satellite"
    container_name: "wyoming-satellite-by02"
    ports:
      - "10700:10700"
    devices:
      - /dev/snd:/dev/snd
    group_add:
      - audio
    command:
      - "--name"
      - "Pi5 BY Y02 Satellite"
      - "--uri"
      - "tcp://0.0.0.0:10700"
      - "--mic-command"
      - "arecord -D plughw:CARD=Y02,DEV=0 -r 16000 -c 1 -f S16_LE -t raw"
      - "--snd-command"
      - "aplay -D plughw:CARD=Y02,DEV=0 -r 22050 -c 1 -f S16_LE -t raw"
      - "--wake-uri"
      - "tcp://openwakeword:10400"
      - "--wake-word-name"
      - "ok_nabu"
      - "--mic-auto-gain"
      - "8"
      - "--mic-noise-suppression"
      - "2"
      - "--mic-volume-multiplier"
      - "1.2"
      - "--snd-volume-multiplier"
      - "1.0"
      - "--awake-wav"
      - "/app/sounds/awake.wav"
      - "--done-wav"
      - "/app/sounds/done.wav"
      - "--debug"
    depends_on:
      - openwakeword
    networks:
      - wyoming-network

  openwakeword:
    image: "rhasspy/wyoming-openwakeword"
    container_name: "openwakeword"
    ports:
      - "10400:10400"
    command:
      - "--uri"
      - "tcp://0.0.0.0:10400"
      - "--preload-model"
      - "ok_nabu"
      - "--debug"
    networks:
      - wyoming-network

  whisper:
    image: "rhasspy/wyoming-whisper"
    container_name: "whisper"
    ports:
      - "10300:10300"
    command:
      - "--uri"
      - "tcp://0.0.0.0:10300"
      - "--debug"
    networks:
      - wyoming-network

  piper:
    image: "rhasspy/wyoming-piper"
    container_name: "piper"
    ports:
      - "10200:10200"
    command:
      - "--uri"
      - "tcp://0.0.0.0:10200"
      - "--debug"
    networks:
      - wyoming-network

networks:
  wyoming-network:
    driver: bridge
